edition = "2024"
group_imports = "StdExternalCrate"
hex_literal_case = "Upper"
imports_granularity = "Crate"
imports_layout = "HorizontalVertical"
match_block_trailing_comma = true
max_width = 120
use_field_init_shorthand = true
use_try_shorthand = true
