apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: seitai
spec:
  serviceName: seitai
  selector:
    matchLabels:
      app: seitai
  template:
    metadata:
      labels:
        app: seitai
    spec:
      initContainers:
        - name: seitai-migration
          image: ghcr.io/hexium310/seitai
          imagePullPolicy: Always
          command:
            - /seitai
          args:
            - migration
            - apply
          env:
            - name: NO_COLOR
              value: '1'
            - name: PGHOST
              value: seitai-database
            - name: PGDATABASE
              value: seitai
            - name: PGUSER
              value: seitai
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: seitai.seitai-database.credentials.postgresql.acid.zalan.do
                  key: password
      containers:
        - name: seitai
          image: ghcr.io/hexium310/seitai
          imagePullPolicy: Always
          env:
            - name: NO_COLOR
              value: '1'
            - name: VOICEVOX_HOST
              value: voicevox
            - name: KANATRANS_HOST
              value: kanatrans
            - name: KANATRANS_PORT
              value: "8080"
            - name: DISCORD_TOKEN
              valueFrom:
                secretKeyRef:
                  name: seitai-secret
                  key: token
            - name: PGHOST
              value: seitai-database
            - name: PGDATABASE
              value: seitai
            - name: PGUSER
              value: seitai
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: seitai.seitai-database.credentials.postgresql.acid.zalan.do
                  key: password
        - name: restarter
          image: ghcr.io/hexium310/seitai
          imagePullPolicy: Always
          command:
            - /seitai
          args:
            - restarter
          env:
            - name: NO_COLOR
              value: '1'
            - name: DISCORD_TOKEN
              valueFrom:
                secretKeyRef:
                  name: seitai-secret
                  key: token
      serviceAccountName: restarter
