name: CD
on:
  push:
    tags:
      - '**'

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Set environment variables
        run: |
          ref_name=${{ github.ref_name }}
          echo TARGETS=${ref_name%/*} >> $GITHUB_ENV
          echo VERSION=${ref_name#*/} >> $GITHUB_ENV
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: hexium310
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build image
        id: build
        uses: docker/bake-action@v6
        with:
          push: true
          targets: ${{ env.TARGETS }}
          set: |
            *.cache-from=type=gha,scope=cache-${{ env.TARGETS }}
            *.cache-to=type=gha,scope=cache-${{ env.TARGETS }},mode=max
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: Set up kubectl
        uses: azure/setup-kubectl@v4
      - name: Set up ID token
        uses: actions/github-script@v7
        id: id-token
        with:
          result-encoding: string
          script: |
            return await core.getIDToken('k8s.chitoku.jp');
      - name: Set context
        run: |
          kubectl config set-cluster k8s.chitoku.jp --server=https://k8s.chitoku.jp
          kubectl config set-credentials github-actions --token=${{ steps.id-token.outputs.result }}
          kubectl config set-context k8s.chitoku.jp --cluster=k8s.chitoku.jp --user=github-actions --namespace=seitai
          kubectl config use-context k8s.chitoku.jp
      - name: Rollout restart
        run: |
          kubectl rollout restart statefulset/seitai
