name: Tag
on:
  pull_request:
    types:
      - closed
    branches:
      - master

permissions:
  contents: write

jobs:
  tag:
    name: Create tag
    runs-on: ubuntu-22.04
    if: github.event.pull_request.merged && startsWith(github.event.pull_request.head.ref, 'release/')
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.TAG_CREATION_GITHUB_TOKEN }}
      - name: Create and push tag
        run: |
          ref=${{ github.event.pull_request.head.ref }}
          package=${ref#release/}
          version=$(
            cargo metadata --format-version=1 --no-deps | \
              jq --raw-output --arg package "$package" '.packages | map(select(.name == $package)) | .[0].version | select(. != null)'
          )
          [[ -z $version ]] && exit 1
          tag="$package/$version"
          git tag $tag
          git push origin $tag
